# permissions for end users to edit templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: template
    app.kubernetes.io/managed-by: kustomize
  name: template.openshift.io-template-editor-role
rules:
- apiGroups:
  - template.openshift.io.templates.cocktail-virt.io
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - template.openshift.io.templates.cocktail-virt.io
  resources:
  - templates/status
  verbs:
  - get
